# Update User Profile
# PUT http://localhost:3000/api/user/profile/6930063477bdbd4c43e863aa
# Content-Type: application/json
# Authorization: Bearer YOUR_JWT_TOKEN_HERE

# {
#   "name": "Shakir jamal",
#   "phone": "8675867483",
#   "email": "ameeralivk1875@gmail.com"
# }

# POST http://localhost:3000/api/user/profile/verify-email-otp
# Content-Type: application/json
# Authorization: Bearer YOUR_JWT_TOKEN_HERE

# {
#   "email": "ameeralivk1875@gmail.com",
#   "otp": "626107"
# }


### Update restaurant image
# PUT http://localhost:3000/api/user/profile/6930063477bdbd4c43e863aa/image
# Content-Type: multipart/form-data; boundary=boundary

# --boundary
# Content-Disposition: form-data; name="profileImage"; filename="pexels-pixabay-414660.jpg"
# Content-Type: image/jpeg

# < ./assets/pexels-pixabay-414660.jpg
# --boundary--

### Get all orders with pagination and search
# POST http://localhost:3000/api/user/orders/695f36345fa15289d991c96c/cancell
# Content-Type: application/json
# Authorization: Bearer YOUR_JWT_TOKEN_HERE

# {
#   "userId":"6930063477bdbd4c43e863aa"
# }

# GET http://localhost:3000/api/user/wallet
# Content-Type: application/json

# {
#   "userId":"6930063477bdbd4c43e863aa"
# }

# POST http://localhost:3000/api/user/varients
# Content-Type: application/json

# {
#   "name": "Size",
#   "Varients": [
#     { "name": "Half" },
#     { "name": "Full" }
#   ]
# }
# PUT http://localhost:3000/api/user/varients/696c7d88389ac1dcec6c81f8
# Content-Type: application/json

# {
#   "name": "Portion Size",
#   "Varients": [
#     { "name": "Half" },
#     { "name": "Full" },
#     { "name": "Family" }
#   ]
# }

# DELETE  http://localhost:3000/api/user/varients/696c7d88389ac1dcec6c81f8
# Content-Type: application/json


GET http://localhost:3000/api/user/varients?page=1&limit=5









