### Block user
GET   http://localhost:3000/api/superadmin/subcategory/692ea36738a54f8d01ed6747
Content-Type: application/json

{
 "name":"Ravi",
 "description":"drink 9",
 "categoryId":"692ea36738a54f8d01ed6757",
 "restaurantId":"692ea36738a54f8d01ed6747"
}

