POST http://localhost:3000/api/admin/auth/signup
Content-Type: application/json

{
  "restaurantName": "My Restaurant",
  "email": "shehimavk@gmail.com",
  "password": "Abcd@1234",
  "role":"admin"
}
