
export const TYPES = {
  PaymentRepository: Symbol("PaymentService"),
  PaymentService:Symbol("PaymentService"),
  PaymentController:Symbol("PaymentController"),
  AdminPlanRepository:Symbol("AdminPlanRepository"),
  AdminPlanService:Symbol("AdminPlanService"),
  AdminPlanControler:Symbol("AdminPlanController"),
  SuperAdminController:Symbol("SuperAdminController"),
  SuperAdminService:Symbol("SuperAdminService"),
  AdminAuthRepository:Symbol("AdminAuthRepository"),
  UserAuthController:Symbol("UserAuthController"),
  UserAuthRepository:Symbol("UserAuthRepository"),
  UserAuthService:Symbol("UserAuthService"),
  AdminAuthService:Symbol("AdminAuthService"),
  AdminAuthController:Symbol("AdminAuthController"),
  SubcriptionRepo:Symbol("SubcriptionRepo"),
  SubcriptionService:Symbol("SubcriptionServer"),
  SubscriptionController:Symbol("SubscriptionController"),
  staffController:Symbol("staffController"),
  staffRepository:Symbol("staffRepository"),
  staffService:Symbol("staffService"),
  staffAuthService:Symbol("staffAuthService"),
  staffAuthController:Symbol("staffAuthController"),
  tableRepository:Symbol("tableRepository"),
  tableService:Symbol("tableService"),
  tableController:Symbol("tableController"),
  userController:Symbol("userController"),
  userService:Symbol("userService"),
  userRepository:Symbol("userRepository"),

};
